// old/client/AdminUsersPage.svelte
<script lang="ts">
  import _ from "lodash"
  import { onMount } from "svelte"
  import { navigate } from "svelte-navigator"
  import type { User } from "../common/api"
  import AdminLayout from "./AdminLayout.svelte"
  import sprachy from "./sprachy"
  let users: User[] = []

  onMount(async () => {
    users = await sprachy.api.admin.listUsers()
  })

  function editUser(userId: string) {
    navigate(`/admin/users/${userId}`)
  }
</script>

<AdminLayout>
  <h1>Users</h1>
  <table class="table table-bordered mt-2">
    <thead>
      <tr>
        <th>Email</th>
        <th>Role</th>
      </tr>
    </thead>
    {#each users as user}
      <tr on:click={() => editUser(user.id)}>
        <td>{user.email}</td>
        <td>{user.isAdmin ? "Admin" : "User"}</td>
      </tr>
    {/each}
  </table>
</AdminLayout>

<style lang="sass">
h1
  font-size: 2.2rem
  margin-bottom: 1.5rem
tr
  cursor: pointer
</style>

// client/AdminUsersPage.vue
<template>
  <admin-layout>
    <b-table-simple class="mt-2">
      <b-thead>
        <b-tr>
          <b-th>Email</b-th>
          <b-th>Role</b-th>
        </b-tr>
      </b-thead>
      <b-tr v-for="user in users" :key="user.name" @click="editUser(user.id)">
        <td>{{ user.email }}</td>
        <td>{{ user.isAdmin ? "Admin" : "User" }}</td>
      </b-tr>
    </b-table-simple>
  </admin-layout>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator"
import _ from "lodash"
import type { User } from "../common/api"

@Component({
  components: {},
})
export default class AdminUsersPage extends Vue {
  users: User[] = []

  async mounted() {
    this.users = await this.$api.admin.listUsers()
  }

  async editUser(userId: string) {
    await this.$routing.navigate(`/admin/users/${userId}`)
  }
}
</script>

<style lang="sass">
tr
  cursor: pointer
</style>
