// client/FrontPage.svelte
<script lang="ts">
  import sprachy from "./sprachy"
  import _ from "lodash"
  import { SprachyAPIValidationError } from "./SprachyAPIClient"
  import { navigate } from "svelte-navigator"
  import { onMount } from "svelte"

  let email: string = ""
  let password: string = ""
  // let afterAuthUrl: string = "";
  let errors: SprachyAPIValidationError["messagesByField"] = {}

  onMount(() => {
    if (sprachy.user) {
      navigate("/home")
    }
  })

  async function signup() {
    try {
      const summary = await sprachy.api.signUp({ email, password })
      sprachy.initApp(summary)
      navigate("/home")
    } catch (err: any) {
      if (err instanceof SprachyAPIValidationError) {
        errors = err.messagesByField
      } else {
        throw err
      }
    }
  }
</script>

<div class="frontpage">
  <header class="container">
    <a class="logo" href="/"> Sprachy </a>
  </header>
  <main class="container">
    <div class="w-50">
      <h1>Learn German the weird and dorky way</h1>
      <p>
        Language-learning apps too often focus on boring, everyday examples.
        Sprachy guarantees the involvement of 100% more cute psychic squirrels
        from beyond the interdimensional veil.
      </p>
      <form on:submit|preventDefault={signup}>
        <fieldset class="form-group">
          <label for="email">Email</label>
          <input
            bind:value={email}
            name="email"
            id="email"
            type="email"
            class="form-control"
            placeholder="Email"
            required
          />
          {#if errors.email}
            <div class="invalid-feedback">
              {errors.email}
            </div>
          {/if}
        </fieldset>
        <fieldset class="form-group">
          <label for="password">Password</label>
          <input
            bind:value={password}
            name="password"
            id="password"
            type="password"
            class="form-control"
            placeholder="Password"
            minLength="10"
            required
          />
          {#if errors.password}
            <div class="invalid-feedback">
              {errors.password}
            </div>
          {/if}
        </fieldset>
        <!-- <input type="hidden" name="then" :value="afterAuthUrl" /> -->
        <button class="btn btn-lg text-white" type="submit"
          >Sign up for Sprachy</button
        >
        <p class="text-warning mt-2">
          <em
            >Sprachy is still early in development; you might want to come back
            later!</em
          >
        </p>
      </form>
    </div>
  </main>
</div>

<style lang="sass">
a:first-child
  margin-right: 1rem

a:last-child
  margin-left: 1rem

.frontpage
  height: 100vh
  background-image: url(./img/sprachy-bg.jpg)
  background-size: cover
  background-position: 50% 75%
  display: flex
  flex-direction: column

.frontpage::before
  content: ''
  position: absolute
  top: 0
  left: 0
  width: 100%
  height: 100%
  background-color: rgba(0,0,0,0.4)

.form-group
  margin-bottom: 1rem

header
  color: white

main.container
  position: relative
  flex-grow: 1
  padding-top: 8rem
  color: white

  h1
    font-size: 3.3rem

  .btn
    background-color: #cd5527
    border-color: #cd5527
</style>

// client/FrontPage.vue
<template>
  <div class="frontpage">
    <header>
      <b-navbar toggleable="md" type="dark">
        <b-container>
          <b-navbar-toggle target="nav_collapse" />

          <b-navbar-brand to="/"> Sprachy </b-navbar-brand>

          <b-collapse id="nav_collapse" is-nav>
            <!-- Right-aligned nav items -->
            <b-navbar-nav class="ml-auto">
              <b-nav-item to="/login">Sign in</b-nav-item>
            </b-navbar-nav>
          </b-collapse>
        </b-container>
      </b-navbar>
    </header>
    <main class="container">
      <b-row>
        <b-col>
          <h1>Learn German the weird and dorky way</h1>
          <p>
            Language-learning apps too often focus on boring, everyday examples.
            Sprachy guarantees the involvement of 100% more cute psychic
            squirrels from beyond the interdimensional veil.
          </p>
          <form @submit.prevent="signup">
            <b-form-group label="Email">
              <b-input
                name="email"
                id="email"
                className="form-control"
                placeholder="Email"
                required
                v-model="email"
              />
            </b-form-group>
            <b-form-group label="Password">
              <b-input
                name="password"
                id="password"
                type="password"
                className="form-control"
                placeholder="Password"
                :minLength="10"
                required
                v-model="password"
              />
            </b-form-group>
            <input type="hidden" name="then" :value="afterAuthUrl" />
            <b-btn size="lg" type="submit">Sign up for Sprachy</b-btn>
            <div v-if="errorMessage">
              {{ errorMessage }}
            </div>
          </form>
        </b-col>
        <b-col> </b-col>
      </b-row>
    </main>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator"
import _ from "lodash"
@Component({
  components: {},
})
export default class FrontPage extends Vue {
  email: string = ""
  password: string = ""
  afterAuthUrl: string = ""
  errorMessage: string | null = null

  activated() {
    if (this.$user) {
      this.$router.navigateReplace("/home")
    }
  }

  async signup() {
    const { email, password } = this

    try {
      const summary = await this.$api.signUp({ email, password })
      this.$initApp(summary)
      this.$router.navigate("/home")
    } catch (err: any) {
      if (err?.response?.data?.code === "email not found") {
        this.errorMessage = "Invalid email"
      } else {
        throw err
      }
    }
  }
}
</script>

<style lang="sass" scoped>
a:first-child
  margin-right: 1rem

a:last-child
  margin-left: 1rem

.frontpage
  height: 100vh
  background-image: url(./img/sprachy-bg.jpg)
  background-size: cover
  background-position: 50% 75%
  display: flex
  flex-direction: column

.frontpage::before
  content: ''
  position: absolute
  top: 0
  left: 0
  width: 100%
  height: 100%
  background-color: rgba(0,0,0,0.4)

header
  color: white

main.container
  position: relative
  flex-grow: 1
  padding-top: 8rem
  color: white

  h1
    font-size: 3.3rem

  .btn
    background-color: #cd5527
    border-color: #cd5527
</style>
