// client/LTable.vue
<template>
  <b-table-simple class="mt-2 ltable" bordered>
    <b-thead v-if="headerRow">
      <b-tr>
        <b-th v-for="(d, i) in headerRow" :key="i">
          {{ d }}
        </b-th>
      </b-tr>
    </b-thead>
    <b-tbody>
      <b-tr v-for="(row, i) in rows" :key="i">
        <b-td v-for="(d, j) in row" :key="j">
          <sprachdown inline :content="d" />
        </b-td>
      </b-tr>
    </b-tbody>
  </b-table-simple>
</template>

<script lang="ts">
import { Component, Inject, Prop, Vue, Watch } from "vue-property-decorator"
import _ from "lodash"
// @ts-ignore
import lukas from "./img/lukas.png"
// @ts-ignore
import anna from "./img/anna.png"
// @ts-ignore
import squirrel from "./img/squirrel.png"

@Component
export default class LTable extends Vue {
  @Prop({ type: String, default: null }) header!: string | null

  created() {
    this.$debug.ltable = this
  }

  get headerRow() {
    return this.header?.split(" / ")
  }

  get rows() {
    const text = this.$slots.default![0]!.text!
    const lines = text.trim().split("\n")
    return lines.map((l) => l.split(" / "))
  }
}
</script>

<style lang="sass" scoped>
.ltable
  th
    border-bottom: none
</style>

// client/LTable.svelte
<script lang="ts">
  import _ from "lodash"
  import Sprachdown from "./Sprachdown.svelte"
  export let header: string | null = null
  export let text: string

  const headerRow = header?.split(" / ")
  const lines = text.trim().split("\n")
  const rows = lines.map((l) => l.split(" / "))
</script>

<template>
  <table class="mt-2 ltable table table-bordered">
    {#if headerRow}
      <thead>
        <tr>
          {#each headerRow as d}
            <th>
              {d}
            </th>
          {/each}
        </tr>
      </thead>
    {/if}
    <tbody>
      {#each rows as row}
        <tr>
          {#each row as d}
            <td>
              <Sprachdown source={d} />
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</template>

<style lang="sass">
.ltable
  th
    border-bottom: none

  :global(p)
    margin: 0
</style>
