// components/LTable.vue
<script setup lang="ts">
import LTableTranslation from "./LTableTranslation.vue"
import Sprachdown from "./Sprachdown.vue"

const props = defineProps<{
  header?: string,
  content: string,
  translate?: boolean,
  inlines?: boolean
}>()

const state = defineState({
  get headerRow() {
    return props.header?.split(" / ")
  },

  get lines() {
    return props.content.trim().split("\n")
  },

  get rows() {
    return this.lines.map(l => l.split(" / "))
  }
})
</script>

<template>
  <table class="mt-2 ltable table table-bordered">
    <thead v-if="state.headerRow">
      <tr>
        <th v-for="d in state.headerRow">
          {{ d }}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="row in state.rows">
        <td v-for="d in row">
          <template v-if="d !== '_'">
            <LTableTranslation v-if="translate" :original="d" :inline="!!inlines" />
            <Sprachdown v-else :source="d" />
          </template>
        </td>
      </tr>
    </tbody>
  </table>
</template>

<style scoped>
.ltable {
  text-align: center;
}

.ltable th {
  border-bottom: none;
}

.ltable :deep(p) {
  margin: 0;
}
</style>

// client/LTable.svelte
<script lang="ts">
  import _ from "lodash"
  import LTableTranslation from "./LTableTranslation.svelte"
  import Sprachdown from "./Sprachdown.svelte"
  export let header: string | null = null
  export let text: string
  export let translate: boolean = false

  if (translate !== false) {
    translate = true
  }

  const headerRow = header?.split(" / ")
  const lines = text.trim().split("\n")
  const rows = lines.map((l) => l.split(" / "))
</script>

<table class="mt-2 ltable table table-bordered">
  {#if headerRow}
    <thead>
      <tr>
        {#each headerRow as d}
          <th>
            {d}
          </th>
        {/each}
      </tr>
    </thead>
  {/if}
  <tbody>
    {#each rows as row}
      <tr>
        {#each row as d}
          <td>
            {#if translate}
              <LTableTranslation original={d} />
            {:else}
              <Sprachdown source={d} />
            {/if}
          </td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>

<style lang="sass">
.ltable
  text-align: center
  th
    border-bottom: none

  :global(p)
    margin: 0
</style>
