// client/PatternPage.svelte
<script lang="ts">
  import _ from "lodash"
  import { Link } from "svelte-navigator"
  import { sprachdex } from "../common/sprachdex"
  import { NotFoundError } from "./GlobalErrorHandler"
  import SiteLayout from "./SiteLayout.svelte"
  import Sprachdown from "./Sprachdown.svelte"

  export let slug: string

  const pattern = sprachdex.allPatterns.find((p) => p.slug === slug)
  if (!pattern) {
    throw new NotFoundError()
  }
</script>

<SiteLayout title={pattern.title}>
  <div class="pattern">
    <h1>{pattern.title}</h1>
    <Sprachdown source={pattern.explanation} />
    <Link to="/pattern/{pattern.slug}/practice" class="btn btn-primary">
      Practice
    </Link>
  </div>
</SiteLayout>

<style lang="sass">
.pattern
  max-width: 800px
  font-size: 16px
  line-height: 24px
</style>

// client/PatternPage.vue
<template>
  <site-layout>
    <div v-if="pattern">
      <h1>{{ pattern.title }}</h1>
      <sprachdown :content="pattern.explanation" />
      <b-btn variant="primary" :to="`/pattern/${pattern.slug}/practice`">
        Practice
      </b-btn>
    </div>
  </site-layout>
</template>

<script lang="ts">
import { Component, Prop, Vue, Watch } from "vue-property-decorator"
import _ from "lodash"
import type { Pattern } from "../common/api"
import FillblankCard from "./FillblankCard.vue"
import { sprachdex } from "../common/sprachdex"
import { NotFoundError } from "./globalErrorHandling"

@Component<LearnPage>({
  components: {
    FillblankCard,
  },
  metaInfo() {
    return {
      title: this.pattern?.title ? this.pattern?.title + " - Sprachy" : null,
    }
  },
})
export default class LearnPage extends Vue {
  @Prop({ type: String, required: true }) slug!: string

  get pattern() {
    const pattern = sprachdex.allPatterns.find((p) => p.slug === this.slug)

    if (!pattern) {
      throw new NotFoundError()
    }

    return pattern
  }
}
</script>

<style lang="sass">
tr
  cursor: pointer
</style>
