// client/SiteLayout.vue
<!-- Default app layout for logged in users: Navbar, container with router view -->
<template>
  <div>
    <site-header />

    <template v-if="noContainer">
      <slot />
    </template>
    <template v-else>
      <b-container id="main">
        <slot />
      </b-container>
    </template>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator"
import SiteHeader from "./SiteHeader.vue"

@Component({
  components: {
    SiteHeader,
  },
})
export default class SiteLayout extends Vue {
  @Prop({ type: Boolean, default: false }) noContainer!: boolean
}
</script>

<style lang="sass" scoped>
#main
  padding-top: 1.5rem
</style>

// client/SiteLayout.svelte
<script lang="ts">
  import SiteHeader from "./SiteHeader.svelte"

  export let title: string | null = null
</script>

<svelte:head>
  {#if title}
    <title>{title} - Sprachy</title>
  {:else}
    <title>Sprachy</title>
  {/if}
</svelte:head>

<div class="site-layout">
  <SiteHeader />
  <div class="container" id="main">
    <slot />
  </div>
</div>

<style lang="sass" scoped>
#main
  padding-top: 1.5rem
</style>
