// components/Sprachdown.vue
<script setup lang="ts">
import Markdown from 'vue3-markdown-it'
// import SprachdownHTML from "./SprachdownHTML.svelte"

const props = defineProps<{
  source: string
  inline?: boolean
}>()
  // const parsedSource = source.replace(/=[^=\n]+=/, (substring) => {
  //   const highlight = substring.slice(1, -1)
  //   return `<InlineTranslation original="${highlight}"/>`
  // })
</script>

<template>
  <div :class="{ markdown: true, 'markdown-inline': props.inline }">
    <Markdown :source="props.source" />
  </div>
</template>

<style>
.markdown-inline {
  display: inline;
}

.markdown-inline :global(p) {
  margin: 0;
  display: inline;
}
</style>

// client/Sprachdown.svelte
<script lang="ts">
  import _ from "lodash"
  import SvelteMarkdown from "svelte-markdown"
  import SprachdownHTML from "./SprachdownHTML.svelte"

  export let source: string

  export let inline: boolean = false // SvelteMarkdown doesn't seem to support this atm, despite claiming to

  // const parsedSource = source.replace(/=[^=\n]+=/, (substring) => {
  //   const highlight = substring.slice(1, -1)
  //   return `<InlineTranslation original="${highlight}"/>`
  // })
</script>

<div class:markdown={true} class:markdown-inline={inline}>
  <SvelteMarkdown {source} renderers={{ html: SprachdownHTML }} />
</div>

<style lang="sass">
.markdown-inline
  display: inline

.markdown-inline :global(p)
  margin: 0
  display: inline
</style>
