// components/Tip.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
  title?: string
  content: string
}>(), {
  title: "Tip"
})
</script>

<template>
  <div class="tip alert alert-info">
    <strong>{{ props.title }}: </strong>
    <Sprachdown :source="props.content" />
  </div>
</template>

<style scoped>
.tip {
  background-color: transparent;
  border: 2px solid #64b5f6;
  color: #333;
}

.tip :deep(strong) {
  color: #64b5f6 !important;
}

.tip :deep(p):last-child {
  margin-bottom: 0;
}
</style>

// client/Tip.svelte
<script lang="ts">
  import _ from "lodash"
  import Sprachdown from "./Sprachdown.svelte"

  export let text: string
  export let title: string = "Tip"

  const textWithTitle = `**${title}**: ${text}`
</script>

<div class="tip alert alert-info">
  <Sprachdown source={textWithTitle} />
</div>

<style lang="sass">
  .tip
    background-color: transparent
    border: 2px solid #64b5f6
    color: #333

  .tip :global(strong)
    color: #64b5f6 !important

  .tip :global(p):last-child
    margin-bottom: 0
</style>
