// client/UnexpectedErrorModal.svelte
<script lang="ts">
  import type { AxiosError } from "axios"
  import _ from "lodash"
  import Modal from "./Modal.svelte"

  export let error: Error | AxiosError
  export let onDismiss: () => void

  $: axiosError = "response" in error ? (error as AxiosError<any>) : null

  $: serverResponse = axiosError ? axiosError.response : null

  $: serverResponseHTML = serverResponse
    ? _.isString(serverResponse.data)
      ? serverResponse.data
      : `<pre>${JSON.stringify(serverResponse.data, null, 2)}</pre>`
    : null
</script>

<Modal open={true}>
  <div class="modal-header">
    {#if axiosError && serverResponse}
      <h5>
        {serverResponse.data.message || "Server error"}
      </h5>
      <pre>{serverResponse.status} {serverResponse.statusText} from {axiosError
          .config.url}</pre>
      <p>
        Sprachy encountered an unexpected error. Please screenshot this message
        and report it to the development team.
      </p>
      <iframe
        title="Server error details"
        srcdoc={serverResponseHTML || undefined}
      />
    {:else}
      <h5>{error.message}</h5>
      <p>
        Sprachy encountered an unexpected error. Please screenshot this message
        and report it to the development team.
      </p>
    {/if}
    <button type="button" aria-label="Close" class="close" on:click={onDismiss}>
      ×
    </button>
  </div>

  <div class="modal-body">
    <pre>{error.stack}</pre>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" on:click={onDismiss}
      >Continue</button
    >
  </div>
</Modal>

<style lang="sass">
.modal-header
  max-width: 100%
  h5, pre
    color: red

  iframe
    width: 100%
    height: 600px

.modal-body
  pre
    white-space: pre-wrap
    font-size: 80%
</style>

// client/UnexpectedErrorModal.vue
<template>
  <b-modal id="unexpectedErrorModal" v-model="showErrorModal" ok-only size="lg">
    <template slot="modal-header" slot-scope="{ close }">
      <div v-if="serverResponse">
        <h5>
          {{
            serverResponse.data.message
              ? serverResponse.data.message
              : "Server error"
          }}
        </h5>
        <pre
          >{{ serverResponse.status }} {{ serverResponse.statusText }} from {{
            error.config.url
          }}</pre
        >
        <p>
          Sprachy encountered an unexpected error. Please screenshot this
          message and report it to the development team.
        </p>
        <iframe :srcdoc="serverResponseHTML" />
      </div>
      <div v-else>
        <h5>{{ error.message }}</h5>
        <p>
          Sprachy encountered an unexpected error. Please screenshot this
          message and report it to the development team.
        </p>
      </div>
      <button type="button" aria-label="Close" class="close" @click="close()">
        ×
      </button>
    </template>

    <pre>{{ error.stack }}</pre>

    <template slot="modal-ok"> Continue </template>
  </b-modal>
</template>

<script lang="ts">
import type { AxiosError, AxiosResponse } from "axios"
import { Vue, Component, Watch, Prop } from "vue-property-decorator"
import * as _ from "lodash"

@Component
export default class UnexpectedErrorModal extends Vue {
  @Prop({ type: Error, required: true }) error!: Error | AxiosError
  @Prop({ type: Function, required: true }) onDismiss!: () => void
  showErrorModal: boolean = true

  get serverResponse(): AxiosResponse | null {
    return "response" in this.error && this.error.response
      ? this.error.response
      : null
  }

  /** The server response may be HTML or JSON. This represents both as HTML for an iframe. */
  get serverResponseHTML(): string | null {
    if (!this.serverResponse) return null

    if (_.isString(this.serverResponse.data)) return this.serverResponse.data
    else
      return `<pre>${JSON.stringify(this.serverResponse.data, null, 2)}</pre>`
  }

  @Watch("showErrorModal")
  onErrorModalChange() {
    if (!this.showErrorModal) {
      this.onDismiss()
    }
  }
}
</script>

<style lang="sass">
#unexpectedErrorModal
  h5, .modal-header pre
    color: red

  header > div
    max-width: 100%

  pre
    white-space: pre-wrap
    font-size: 80%

  iframe
    width: 100%
    height: 600px
</style>
