// components/AudioForLine.vue
<script setup lang="ts">
import type { SpeechSystem, Base64Audio } from "~/lib/SpeechSystem"
import SoundIndicator from "~/components/SoundIndicator.vue"

const props = withDefaults(defineProps<{
  opts: Partial<Parameters<SpeechSystem["get"]>[0]>
  playImmediately?: boolean,
  disabled?: boolean,
}>(), {
  playImmediately: false,
  disabled: false
})

defineExpose({
  playSound
})

const { speech, user } = useSprachyApp()

const state = defineState({
  playingSound: false,
  loading: true,
  audio: undefined as Base64Audio | undefined,

  get audioOpts() {
    return props.opts.from && props.opts.message
      ? { from: props.opts.from, message: props.opts.message }
      : undefined
  },

  get enabled() {
    return user.enableSpeechSynthesis && this.audioOpts
  }
})

async function loadAudio() {
  state.loading = true
  try {
    state.audio = await speech.get(state.audioOpts!)
  } finally {
    state.loading = false
  }

  if (props.playImmediately) {
    playSound()
  }
}

watchEffect(() => {
  if (state.enabled && !state.audio) {
    loadAudio()
  }
})

async function playSound() {
  if (!state.audio) return

  state.playingSound = true
  try {
    await speech.playAudioContent(state.audio)
  } finally {
    state.playingSound = false
  }
}

onUnmounted(() => {
  // User muted the sound or went to another page, stop playing
  if (state.playingSound) speech.skip()
})
</script>

<template>
  <SoundIndicator v-if="state.enabled" :loading="state.loading" :playing="state.playingSound"
    @click.prevent="props.disabled ? () => null : playSound" />
</template>

// src/lib/AudioForLine.svelte
<script lang="ts">
  import _ from "lodash"
  import sprachy from "$lib/sprachy"
  import SoundIndicator from "$lib/SoundIndicator.svelte"
  import type { SpeechSystem, Base64Audio } from "$lib/SpeechSystem"
  import { onDestroy } from "svelte"

  export let playImmediately: boolean = false
  export let disabled: boolean = false
  export let opts: Partial<Parameters<SpeechSystem["get"]>[0]>

  const { speech, user } = sprachy.expectSPA()
  let playingSound: boolean = false
  let loading = true
  let audio: Base64Audio | undefined
  let playedOnLoad: boolean = false

  $: audioOpts =
    opts.from && opts.message
      ? { from: opts.from, message: opts.message }
      : undefined
  $: enabled = $user?.enableSpeechSynthesis && audioOpts

  async function loadAudio() {
    loading = true
    try {
      audio = await speech.get(audioOpts!)
    } finally {
      loading = false
    }

    if (playImmediately) {
      playedOnLoad = true
      playSound()
    }
  }

  $: if (enabled) {
    loadAudio()
  }

  export async function playSound() {
    if (!audio) return

    playingSound = true
    try {
      await speech.playAudioContent(audio)
    } finally {
      playingSound = false
    }
  }

  onDestroy(() => {
    // User muted the sound or went to another page, stop playing
    if (playingSound) speech.skip()
  })

  $: if (playImmediately && !playedOnLoad) {
    playSound()
  }
</script>

<SoundIndicator
  {loading}
  playing={playingSound}
  on:click={disabled ? () => null : playSound}
/>
