// components/LevelReport.vue
<script setup lang="ts">
import { Ref } from "vue"
import type { PatternId } from "~/lib/Pattern"
import LevelReportItem from "./LevelReportItem.vue"

const props = defineProps<{
  experienceByPatternId: Record<PatternId, number>
}>()

const emit = defineEmits<{
  (event: "animEnd"): void
}>()

const { patternsAndProgress } = useSprachyApp()

const itemRefs = [] as Ref<typeof LevelReportItem>[]

const state = useLocalReactive({
  get gainingPatterns() {
    return patternsAndProgress.filter((p) => p.id in props.experienceByPatternId)
  },

  get items() {
    return this.gainingPatterns.map((p) => {
      const experience = props.experienceByPatternId[p.id]!
      return {
        title: p.title,
        expStart: p.progress.experience - experience,
        expGained: experience,
      }
    })
  }
})
</script>

<template>
  <div>
    <table>
      <LevelReportItem v-for="item in state.items" v-bind="item" ref="itemRefs[i]" @animEnd="emit('animEnd')" />
    </table>

    <!-- <button class="btn btn-debug" on:click={testProgress}>Test</button> -->
  </div>
</template>

<style scoped>
table {
  max-width: 800px;
  margin: auto;
}
</style>

// src/lib/LevelReport.svelte
<script lang="ts">
  import type { PatternId } from "./Pattern"
  import LevelReportItem from "./LevelReportItem.svelte"
  import { createEventDispatcher } from "svelte"
  import sprachy from "./sprachy"

  export let experienceByPatternId: Record<PatternId, number>

  const { patternsAndProgress } = sprachy.expectSPA()

  const dispatch = createEventDispatcher()

  $: gainingPatterns = $patternsAndProgress.filter(
    (p) => p.id in experienceByPatternId
  )

  $: items = gainingPatterns.map((p) => {
    const experience = experienceByPatternId[p.id]!
    return {
      title: p.title,
      expStart: p.progress.experience - experience,
      expGained: experience,
    }
  })

  let itemRefs: LevelReportItem[] = []
</script>

<div>
  <table>
    {#each items as item, i}
      <LevelReportItem
        {...item}
        bind:this={itemRefs[i]}
        on:animEnd={() => dispatch("animEnd")}
      />
    {/each}
  </table>

  <!-- <button class="btn btn-debug" on:click={testProgress}>Test</button> -->
</div>

<style>
  table {
    max-width: 800px;
    margin: auto;
  }
</style>
