// src/lib/ExerciseView.svelte
<script lang="ts">
  import type { Exercise } from "./Exercise"
  import ExerciseViewFillblank from "./ExerciseViewFillblank.svelte"
  import ExerciseViewChoice from "./ExerciseViewChoice.svelte"
  import { createEventDispatcher } from "svelte"
  import type { Pattern } from "./Pattern"

  export let exercise: Exercise
  export let pattern: Pattern
  const dispatch = createEventDispatcher()
</script>

{#if exercise.type === "fillblank"}
  <ExerciseViewFillblank
    {exercise}
    on:correct={() => dispatch("correct")}
    {pattern}
  />
{:else if exercise.type === "choice"}
  <ExerciseViewChoice {exercise} on:correct={() => dispatch("correct")} />
{/if}

<style>
</style>

// components/ExerciseView.vue
<script setup lang="ts">
import type { Exercise } from "~/lib/Exercise"
import ExerciseViewFillblank from "~/components/ExerciseViewFillblank.vue"
import ExerciseViewChoice from "~/components/ExerciseViewChoice.vue"
import type { Pattern } from "~/lib/Pattern"

defineProps<{
  exercise: Exercise
  pattern: Pattern
}>()

const emit = defineEmits<{
  (event: "correct"): void
}>()
</script>

<template>
  <ExerciseViewFillblank v-if="exercise.type === 'fillblank'" :exercise="exercise" :pattern="pattern"
    @correct="emit('correct')" />
  <ExerciseViewChoice v-else-if="exercise.type === 'choice'" :exercise="exercise" @correct="emit('correct')" />
</template>
