// src/lib/Hints.svelte
<script lang="ts">
  import type { MultipleChoiceExercise } from "./Exercise"
  import Sprachdown from "$lib/Sprachdown.svelte"

  type Hint = MultipleChoiceExercise["hint"]
  export let hint: Hint
  export let engaged = false

  async function engage() {
    engaged = !engaged
  }
</script>

<button
  class="btn btn-light"
  class:disengaged={!engaged}
  class:engaged
  on:click={() => engage()}
>
  {#if engaged && hint}
    <Sprachdown inline source={hint} />
  {/if}
  {#if !engaged}
    <Sprachdown inline source={"Hint"} />
  {/if}
</button>

<style>
  button.disengaged {
    background-color: #d1cee9;
  }

  button.engaged {
    background-color: #b7d7da;
  }
</style>

// components/Hints.vue
<script setup lang="ts">
import Sprachdown from "~/components/Sprachdown.vue"

defineProps<{
  hint: string
}>()

const state = useLocalReactive({
  engaged: false
})

async function engage() {
  state.engaged = !state.engaged
}
</script>

<template>
  <button class="btn btn-light" :class="{ 'engaged': state.engaged, 'disengaged': !state.engaged }"
    @click.prevent="engage">
    <Sprachdown v-if="state.engaged" inline :source="hint" />
    <Sprachdown v-else inline source="Hint" />
  </button>
</template>

<style scoped>
button.disengaged {
  background-color: #d1cee9;
}

button.engaged {
  background-color: #b7d7da;
}
</style>
