// src/lib/LearnModeExercises.svelte
<script lang="ts">
  import _ from "lodash"
  import ExerciseView from "$lib/ExerciseView.svelte"
  import sprachy from "$lib/sprachy"
  import { createEventDispatcher } from "svelte"
  import type { Pattern } from "./Pattern"

  const spa = sprachy.expectSPA()
  const { user, speech, progressByPatternId } = spa

  export let pattern: Pattern
  export let expMultiplier: number = 1.0
  const dispatch = createEventDispatcher()

  $: progress = $progressByPatternId[pattern.id]!
  let startLevel: number
  $: if (progress && startLevel == null) {
    startLevel = progress.level
  }

  let exerciseIndex = 0
  $: exercises = Array.from(pattern.exercises)

  $: if (exercises) {
    exerciseIndex = 0
  }
  $: exercise = exercises[exerciseIndex]!

  $: if ($user?.enableSpeechSynthesis) {
    for (const ex of exercises) {
      if (ex.from && ex.message) {
        speech.preload({ from: ex.from, message: ex.message })
      }
    }
  }

  async function nextExercise() {
    // Completed an exercise, gain experience
    const expGained = 200 * expMultiplier
    spa.gainPatternExperience(pattern.id, expGained)

    if (progress.level > startLevel) {
      dispatch("complete")
    } else if (exerciseIndex >= exercises.length - 1) {
      exerciseIndex = 0
    } else {
      exerciseIndex += 1
    }
  }
</script>

<div class="practice">
  <div class="exercises">
    {#key pattern.id + "-" + exerciseIndex}
      <ExerciseView {exercise} on:correct={nextExercise} {pattern} />
    {/key}
  </div>
</div>

<style>
  .practice {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    padding: 2rem 0;
  }
</style>

// components/LearnModeExercises.vue
<script lang="ts" setup>
import ExerciseView from "./ExerciseView.vue"

const props = defineProps<{
  learnable: LearnablePattern
}>()

const emit = defineEmits<{
  (e: "complete"): void
}>()

const state = defineState({
  startLevel: 0,
  exerciseIndex: 0,

  get exercises() {
    return props.learnable.pattern.exercises
  },

  get exercise() {
    return this.exercises[state.exerciseIndex]!
  }
})

watch(
  () => props.learnable,
  () => {
    state.startLevel = props.learnable.pattern.progress.level
    state.exerciseIndex = 0
  },
  { immediate: true }
)

watchEffect(() => {
  if (speech.enabled) {
    for (const ex of props.learnable.pattern.exercises) {
      if (ex.type === 'fillblank')
        speech.preload(ex)
    }
  }
})

async function nextExercise() {
  // Completed an exercise, gain experience
  const expGained = 200
  progressStore.gainPatternExperience(props.learnable.pattern.id, expGained)

  if (props.learnable.pattern.progress.level > state.startLevel) {
    emit("complete")
  } else if (state.exerciseIndex >= state.exercises.length - 1) {
    state.exerciseIndex = 0
  } else {
    state.exerciseIndex += 1
  }
}
</script>

<!-- <svelte:head>
  {#each exercises as exercise}
    {#if "image" in exercise}
      <link rel="preload" as="image" href={exercise.image} />
    {/if}
  {/each}
</svelte:head> -->

<template>
  <div class="practice">
    <div class="exercises">
      <ExerciseView :pattern="learnable.pattern" :exercise="state.exercise" @correct="nextExercise" />
    </div>
  </div>
</template>

<style scoped>
.practice {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  padding: 2rem 0;
}
</style>
