// client/StoryLineReading.svelte
<script lang="ts">
  import _ from "lodash"
  import Message from "./Message.svelte"
  import type { Line } from "../common/Pattern"
  import Sprachdown from "./Sprachdown.svelte"

  export let line: Line
  export let flip: boolean = false
</script>

<Message from={line.from} {flip}>
  {line.message}
  <div slot="after">
    <div class="translation">
      {@html line.translation}
    </div>
    {#if line.explanation}
      <div class="explanation">
        <Sprachdown inline source={line.explanation} />
      </div>
    {/if}
  </div>
</Message>

<style lang="sass">
.explanation
  padding-top: 0.8rem
  color: #444
  font-size: 90%
  color: #0b9bc7
</style>

// components/StoryLineReading.vue
<script setup lang="ts">
import type { ReadingLine } from "~/lib/Pattern"
import Message from "~/components/Message.vue"
import Sprachdown from "~/components/Sprachdown.vue"
import AudioForLine from "~/components/AudioForLine.vue"

defineProps<{
  line: ReadingLine
  flip?: boolean
  staticMode?: boolean
}>()
</script>

<template>
  <div class="reading">
    <Message v-if="line.message" :from="line.from" :flip="flip" :tooltip="line.translation">
      <div>
        <AudioForLine :opts="line" :playImmediately="!staticMode" />
        <Sprachdown inline :source="line.message" />
      </div>
    </Message>
    <img v-if="line.image" :alt="line.imageAlt" :src="line.image" />
  </div>
</template>

<style scoped>
img {
  max-height: 300px;
  margin-top: 1rem;
}
</style>
