// client/LoginPage.svelte
<script lang="ts">
  import { navigate } from "svelte-navigator"
  import sprachy from "./sprachy"

  let email: string = ""
  let password: string = ""
  let errorMessage: string | null = null

  async function login() {
    errorMessage = null

    try {
      const userSummary = await sprachy.api.login({ email, password })
      sprachy.initApp(userSummary)
      navigate("/home")
    } catch (err: any) {
      if (err?.response?.data?.code === "authentication failed") {
        errorMessage = "Invalid email or password"
      } else {
        throw err
      }
    }
  }
</script>

<template>
  <main class="container">
    <form class="form" on:submit|preventDefault={login}>
      <fieldset class="form-group">
        <label for="emailInput">Email</label>
        <input
          name="email"
          id="emailInput"
          placeholder="Email"
          class="form-control"
          required
          bind:value={email}
        />
      </fieldset>
      <fieldset class="form-group mt-2">
        <label for="passwordInput">Email</label>
        <input
          name="password"
          id="passwordInput"
          type="password"
          placeholder="Password"
          class="form-control"
          required
          bind:value={password}
        />
      </fieldset>
      <button class="btn btn-primary mt-2" type="submit">Sign in</button>
      {#if errorMessage}
        <div>
          {errorMessage}
        </div>
      {/if}
      <hr />
      <a href="/">Sign up</a>
    </form>
  </main>
</template>

<style lang="sass">
main
  height: calc(100vh - 5rem)
  display: flex
  align-items: center
  justify-content: center
</style>

// src/LoginPage.vue
<template>
  <main class="container">
    <form @submit.prevent="login">
      <h4 className="mb-4">Login</h4>
      <b-form-group label="Email" label-for="emailInput">
        <b-form-input
          name="email"
          id="emailInput"
          placeholder="Email"
          required
          autofocus
          v-model="email"
        />
      </b-form-group>
      <b-form-group label="Password" label-for="passwordInput" class="mt-2">
        <b-form-input
          name="password"
          id="passwordInput"
          type="password"
          placeholder="Password"
          required
          v-model="password"  
        />
      </b-form-group>
      <input type="hidden" name="then" :value="afterAuthUrl" />
      <b-btn type="submit" class="mt-2">Login</b-btn>
      <div v-if="errorMessage">
        {{errorMessage}}
      </div>
    </form>
  </main>
</template>

<script lang="ts">
import { getAuth, signInWithEmailAndPassword } from "firebase/auth"

const auth = getAuth()

import { Component, Vue } from "vue-property-decorator"
import _ from "lodash"
@Component({
  components: {},
})
export default class LoginPage extends Vue {
  email: string = ""
  password: string = ""
  afterAuthUrl: string = ""
  errorMessage: string|null = null

  async login() {
    this.errorMessage = null
    const { email, password } = this
    try {
      await signInWithEmailAndPassword(
        auth,
        email,
        password
      )
    } catch (err) {
      this.errorMessage = err.message
    }
  }

  postLoginRedirect() {
    this.$app.router.replace({
      name: 'home'
    })
  }
}
</script>

<style lang="sass">
main
  height: calc(100vh - 5rem)
  display: flex
  align-items: center
  justify-content: center
</style>
